name: Build And Deploy
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-python-app:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Analyse code with pylint
      run: |
        find . -name '*.py' -exec pylint {} \;
    - name: Unit Testing
      run: |
        python tests.py

  build-docker-app:

    runs-on: ubuntu-latest
    needs: 
      - build-python-app
    steps:
    - uses: actions/checkout@v2
    - name: Lint Dockerfile
      uses: hadolint/hadolint-action@v1.4.0
      with:
        dockerfile: Dockerfile
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag file-system-server:$(date +%s)

  slack-workflow-notification:
    if: ${{ github.event.pull_request.merged }} == true
    runs-on: ubuntu-latest
    name: Slack Workflow Notification
    needs:
      - build-docker-app
    steps:
      - name: Post the status to slack
        uses: Gamesight/slack-workflow-status@master
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          slack_webhook_url: ${{secrets.SLACK_WEBHOOK_URL}}

      



    
